# -*- coding: utf-8 -*-
{
    'name': "Tahboub Sales Customization.",
    'description': "",
    'summary': "",
    'version': '19.0.1',
    'author': "Hossam Zaki - Flex-Ops",
    'website': "https://flex-ops.com",
    'category': '',
    'license': 'LGPL-3',
    'depends': ['base',
                'product',
                'sale',
                'sales_team',
                'sale_stock',
                'stock',
                'sale_crm',
                'analytic',
                'flex_currencies_reports',
                ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',

        'views/res_config_settings.xml',
        'views/sale_order.xml',
        'views/sale_order_line.xml',
        'views/sale_order_categ.xml',
        'views/product.xml',
        'views/custom_rate.xml',

        'wizards/set_discount.xml',

        'reports/sale_abbreviated.xml',
        'reports/sale_detailed.xml',
        'reports/sale.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
