{
    'name': 'Flex Sale Without Brand',
    'version': '1.0',
    'summary': '',
    'description': '',
    'category': '',
    'author': 'Sohaib Alamleh||Flex-ops',
    'website': '',
    'license': '',
    'depends': ['base', 'sale'],
    'data': ['reports/sale.xml'],
    'demo': [''],
    'installable': True,
    'auto_install': False,
}